# Generated by Django 4.2.5 on 2023-09-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='name_of_menu_ordered',
        ),
        migrations.AddField(
            model_name='orders',
            name='table_of_order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Ordering.tables'),
        ),
        migrations.AddField(
            model_name='orders',
            name='waiter',
            field=models.CharField(default="waiter's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Order_history',
        ),
    ]
