# Generated by Django 4.2.5 on 2023-10-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0002_rename_name_orders_name_of_menu_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('ONGOING', 'ONGOING')], default='NONE', max_length=30),
        ),
    ]
